diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.3
    wheel_radius: 0.05
    cmd_vel_timeout: 0.5
    velocity_rolling_window_size: 2
    publish_rate: 50
    odom_frame: "odom"
    base_frame: "base_link"
    use_stamped_vel: false

